services:
  frontend:
    image: ${DOCKER_USERNAME}/manhwa-frontend:${TAG:-latest}
    container_name: manhwa-frontend-prod
    ports:
      - "8081:80"
    restart: always
    networks:
      - manhwa-network
networks:
  manhwa-network:
    external: true